# Generated by Django 5.2.17 on 2026-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
